// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sqliteexporter")
	ScopeName = "otelcol/sqliteexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
